import re

def persName(text):
    """Apply tags to the regex

    :param text str: person that has to be encoded
    :returns: person encoded with the proper tag
    :rtype: str
    """

    #This series of statements contains regex of persons from the corpus
    p0001 = re.compile(r"(Madame )?(M. ?)?(Baron )?(D|d)('|’)E(STOURNELLES|stournelles)( (de|DE) C(ONSTANT|onstant))?")
    p0002 = re.compile(r"((M(.|onsieur|adame) ?)?((le )?P(résident|RÉSIDENT) ?)?((N|H)(.|icholas)? ?)?(M(urray|.) ?)?)?B(u(l)?tler|UTLER)")
    p0003 = re.compile(r"Major ABBOTT")
    p0004 = re.compile(r"M. Abrami")
    p0005 = re.compile(r"Paul Adam")
    p0006 = re.compile(r"(M.|(B|b)aron) A(delsward|DELSWARD)")
    p0007 = re.compile(r"Felix Alcan")
    p0008 = re.compile(r"Miss Alexander")
    p0009 = re.compile(r"Alexandre le Grand")
    p0010 = re.compile(r"Almereyda")
    p0011 = re.compile(r"Amelot")
    p0012 = re.compile(r"(M(e)?lle.? ?) A(MELOT|melot)")
    p0013 = re.compile(r"(C|c)ardinal Amette")
    p0014 = re.compile(r"FERN ANDREWS")
    p0015 = re.compile(r"ANDRIEUX")
    p0016 = re.compile(r"ANGELL")
    p0017 = re.compile(r"Anibal MAURTUA")
    p0018 = re.compile(r"Anselmo V. BARRETO")
    p0019 = re.compile(r"(M.|Alexandre) ANTONIADES (Alexandre )")
    p0020 = re.compile(r"Antonio MUO")
    p0021 = re.compile(r"((M.)? ?(P.)?(Paul)? )?A(ppell|PPELL)")
    p0022 = re.compile(r"Apponyi")
    p0023 = re.compile(r"Archimède")
    p0024 = re.compile(r"Aristide Briand")
    p0025 = re.compile(r"Armez")
    p0026 = re.compile(r"Artaban")
    p0027 = re.compile(r"Arturo GARCIA")
    p0028 = re.compile(r"Attila")
    p0029 = re.compile(r"Amiral Aube")
    p0030 = re.compile(r"Révérend J.B.ASHAM")
    p0031 = re.compile(r"Aubigné")
    p0032 = re.compile(r"Augagneur")
    p0033 = re.compile(r"Auguste Gauvain")
    p0034 = re.compile(r"Auguste Lalance")
    p0035 = re.compile(r"(M. )?A(ulard|ULARD)")


    #This series of statements contains the encoding for the persons from the corpus
    text = re.sub(p0001, r'<persName ref="#p0001" type="pec">\g<0></persName>', text)
    text = re.sub(p0002, r'<persName ref="#p0002" type="pec">\g<0></persName>', text)
    text = re.sub(p0003, r'<persName ref="#p0003" type="pec">\g<0></persName>', text)
    text = re.sub(p0004, r'<persName ref="#p0004" type="pec">\g<0></persName>', text)
    text = re.sub(p0005, r'<persName ref="#p0005" type="pec">\g<0></persName>', text)
    text = re.sub(p0006, r'<persName ref="#p0006" type="pec">\g<0></persName>', text)
    text = re.sub(p0007, r'<persName ref="#p0007" type="pec">\g<0></persName>', text)
    text = re.sub(p0008, r'<persName ref="#p0008" type="pec">\g<0></persName>', text)
    text = re.sub(p0009, r'<persName ref="#p0009" type="pec">\g<0></persName>', text)
    text = re.sub(p0010, r'<persName ref="#p0010" type="pec">\g<0></persName>', text)
    text = re.sub(p0011, r'<persName ref="#p0011" type="pec">\g<0></persName>', text)
    text = re.sub(p0012, r'<persName ref="#p0012" type="pec">\g<0></persName>', text)
    text = re.sub(p0013, r'<persName ref="#p0013" type="pec">\g<0></persName>', text)
    text = re.sub(p0014, r'<persName ref="#p0014" type="pec">\g<0></persName>', text)
    text = re.sub(p0015, r'<persName ref="#p0015" type="pec">\g<0></persName>', text)
    text = re.sub(p0016, r'<persName ref="#p0016" type="pec">\g<0></persName>', text)
    text = re.sub(p0017, r'<persName ref="#p0017" type="pec">\g<0></persName>', text)
    text = re.sub(p0018, r'<persName ref="#p0018" type="pec">\g<0></persName>', text)
    text = re.sub(p0019, r'<persName ref="#p0019" type="pec">\g<0></persName>', text)
    text = re.sub(p0020, r'<persName ref="#p0020" type="pec">\g<0></persName>', text)
    text = re.sub(p0021, r'<persName ref="#p0021" type="pec">\g<0></persName>', text)
    text = re.sub(p0022, r'<persName ref="#p0022" type="pec">\g<0></persName>', text)
    text = re.sub(p0023, r'<persName ref="#p0023" type="pec">\g<0></persName>', text)
    text = re.sub(p0024, r'<persName ref="#p0024" type="pec">\g<0></persName>', text)
    text = re.sub(p0025, r'<persName ref="#p0025" type="pec">\g<0></persName>', text)
    text = re.sub(p0026, r'<persName ref="#p0026" type="pec">\g<0></persName>', text)
    text = re.sub(p0027, r'<persName ref="#p0027" type="pec">\g<0></persName>', text)
    text = re.sub(p0028, r'<persName ref="#p0028" type="pec">\g<0></persName>', text)
    text = re.sub(p0029, r'<persName ref="#p0029" type="pec">\g<0></persName>', text)
    text = re.sub(p0030, r'<persName ref="#p0030" type="pec">\g<0></persName>', text)
    text = re.sub(p0031, r'<persName ref="#p0031" type="pec">\g<0></persName>', text)
    text = re.sub(p0032, r'<persName ref="#p0032" type="pec">\g<0></persName>', text)
    text = re.sub(p0033, r'<persName ref="#p0033" type="pec">\g<0></persName>', text)
    text = re.sub(p0034, r'<persName ref="#p0034" type="pec">\g<0></persName>', text)
    text = re.sub(p0035, r'<persName ref="#p0035" type="pec">\g<0></persName>', text)
    return text